baseURL = "https://claudebourdin-eng.github.io/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "Meli-Melo 973"
theme = "poemes-theme"
paginate = 20

[params]
  author = "Meli-Melo 973"
  subtitle = "Meli-Melo 973"
  description = "Un jardin de mots, de rimes et d emotions."

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
