baseURL = "https://claudebourdin-eng.github.io/melimelo973-site/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "MÃ©li-MÃ©lo 973"
theme = "poemes-theme"
paginate = 20

[params]
  author      = "MÃ©li-MÃ©lo 973"
  subtitle    = "âœ¨ MÃ©li-MÃ©lo 973"
  description = "Un jardin de mots, de rimes et d'Ã©motions."

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
